package ch.stair.platypus.models;

import java.util.Date;
import java.util.List;

import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Keep;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.Box;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;

/**
 * Created by philipp on 10.05.17.
 */

@Entity
public class Comments {
    @Id
    private long id;

    private String comment_text;
    private Date created;
    private Boolean deleted;

    @Generated(1928670080)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Comments(long id, String comment_text, Date created, Boolean deleted) {
        this.id = id;
        this.comment_text = comment_text;
        this.created = created;
        this.deleted = deleted;
    }
    @Generated(1094291921)
    public Comments() {
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getComment_text() {
        return comment_text;
    }
    public void setComment_text(String comment_text) {
        this.comment_text = comment_text;
    }
    public Date getCreated() {
        return created;
    }
    public void setCreated(Date created) {
        this.created = created;
    }
    public Boolean getDeleted() {
        return deleted;
    }
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

}
