package ch.stair.platypus.repository.models;

import java.util.Date;
import java.util.List;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToMany;

@Entity
public class Feedback {
    @Id(assignable = true)
    private long id;

    private String feedbackText;
    private Date creationDate;
    private Integer votesCount;

    @Backlink
    public List<FeedbackHashtag> feedbackHashtagses = new ToMany<>(this, Feedback_.feedbackHashtagses);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(2144120763)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Feedback(long id, String feedbackText, Date creationDate, Integer votesCount) {
        this.id = id;
        this.feedbackText = feedbackText;
        this.creationDate = creationDate;
        this.votesCount = votesCount;
    }

    @Generated(802671868)
    public Feedback() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFeedbackText() {
        return feedbackText;
    }

    public void setFeedbackText(String feedbackText) {
        this.feedbackText = feedbackText;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Integer getVotesCount() {
        return votesCount;
    }

    public void setVotesCount(Integer votesCount) {
        this.votesCount = votesCount;
    }
}
